#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3
bspc config top_padding          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false
bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"

bspc rule -a Nestopia desktop='^4' state=floating follow=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty state=floating

# Border
bspc config focused_border_color        "#ffc52a"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Autostart
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/dunst &
# nitrogen --restore &
nitrogen --random --set-zoom-fill /home/omk/Pictures/WP &
picom -CGb &
nm-applet --indicator &
~/.config/bspwm/scripts/low_bat_notifier.sh
megasync &
sleep 3 && insync start &
libinput-gestures-setup start &
$HOME/.config/polybar/bspwm.sh &
$HOME/.config/conky/launch.sh &

# disable DPMS screen blanking
xset s off -dpms &
xset s noblank &
